import { CaseHistory } from './caseHistory';
import { CaseMovement } from './caseMovement';
import { CasePayment } from './casePayment';
import { Client } from './client';
import { Council } from './council';
import { Court } from './court';
import { File } from './file';
import { KeyValuePair } from './keyValuePair';
import { Note } from './note';
import { RegistrationMark } from './registrationMark';
import { StateChange } from './stateChange';

export interface Case {
  id: number;
  stateChanges: StateChange[];
  internalMark: string;
  dateCreated: Date;
  dateUpdated: Date;
  clientId: number;
  court: Court;
  respondent: Client;
  prosecutor: Client;
  council: Council;
  registrationMark: RegistrationMark;
  caseNumber: string;
  year: string;
  caseTitle: string;
  subject: string;
  caseValue: string;
  notes: Note[];
  files?: File[];
  evidences?: File[];
  hearingMinutes?: File[];
  expertises?: File[];
  decisions?: File[];
  other?: File[];
  status: KeyValuePair;
  active: boolean;
  caseHistory?: CaseHistory[];
  caseMovements?: CaseMovement[];
  payments?: CasePayment[];
}
